spring:
  # jms:
  #   template:
  #     default-destination: tacocloud.order.queue
  #   listener:
  #     auto-startup: true
  # artemis:
  #   broker-url: tcp://localhost:61616
  #   user: hoang92Taco
  #   password: hoang92Taco
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.order.queue
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.sia.kitchen.StringDeserializer
server:
  port: 4444

